# Tugas 1

## Import data

In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/Opensourcefordatascience/Data-sets/master/blood_pressure.csv"
df = pd.read_csv(url)

In [5]:
df.head()

   patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141

## Mengolah data numeric ke bentuk statistik deskriptif

Statistik deskriptif adalah metode yang berkaitan dengan pengumpulan / penyajian data hingga memberi informasi yang berguna.



**Mean (rata-rata)**

* Data Tunggal

  $$
\begin{align*}
\displaystyle\bar x &= \frac{x_{1} + x_{2} + x_{3} + ... + x_{n}}{n} \\
  keterangan &: \\
\bar x &=\ Rata-rata \\
x_{1} + x_{2} + x_{3} + ... + x_{n} &=\ Nilai \  data \\
n &=\ Banyaknya \ data
\end{align*}
$$

* Data kelompok

  Mean data kelompok artinya data memiliki pengelompokkan dalam interval-interval kelas yang sama panjang. Untuk mengetahui nilai mediannya dapat ditentukan dengan rumus berikut ini.

$$
\begin{align*}
\displaystyle
\bar x &= \frac{\sum f_{i}x_{i}}{n} \\
keterangan &: \\
\bar x &=\ Rata-rata \\
f_{i} &=\ Frekuensi \\
x_{i} &=\ Nilai \ tengah \\
n &=\ Total \ frekuensi \ atau \ data
\end{align*}
$$

**Modus (data yang sering muncul)**

* Data Kelompok

  Modus data kelompok Modus data kelompok dirumuskan sebagai berikut:

  $$
\begin{align*}
\displaystyle
M_{o} &= L + c\left( \frac{d_{1}}{d_{1} + d_{2}} \right)c \\
\end{align*}
$$

**Kuartil**
  
  Kuartil adalah membagi data yang telah diurutkan menjadi empat bagian yang sama banyak. Kuartil data tunggal Urutkan data dari yang kecil ke yang besar, kemudian tentukan kuartil dengan rumus sebagai berikut: 

$$
\begin{align*}
\displaystyle
Q_{i} &= \frac{i\left( n + 1 \right)}{4}
\end{align*}
$$

**Jangkauan**

  Apabila sekumpulan data sudah diurutkan dari yang terkecil sampai terbesar maka Range dari data itu adalah
<br>

  Range = data terbesar – data terkecil

  Contohnya tentukan range dari data 15, 20, 25 , 35, 40, 43, 50!

  Cara menjawabnya:
  Data terbesarnya = 50
  Data terkecilnya = 15

  Range = 50 – 15 = 35

$$
\begin{align*}
\displaystyle
J &= X_{max} - X_{min}
\end{align*}
$$

In [6]:
df.describe()

          patient   bp_before    bp_after
count  120.000000  120.000000  120.000000
mean    60.500000  156.450000  151.358333
std     34.785054   11.389845   14.177622
min      1.000000  138.000000  125.000000
25%     30.750000  147.000000  140.750000
50%     60.500000  154.500000  149.500000
75%     90.250000  164.000000  161.000000
max    120.000000  185.000000  185.000000

## Perhitungan

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

menentukan dataframe

In [8]:
xy = df['bp_before']

Mean

In [9]:
mean = xy.mean()
print('Mean: ',mean)

Mean:  156.45

Median

In [10]:
median = xy.median() 
print('Median: ',median)

Median:  154.5

Modus

In [11]:
modus = xy.mode()
print('Modus: ',modus[0])

Modus:  142

Kuartil

In [12]:
kuartil=xy.quantile() 
print('Kuartil: ', kuartil)

Kuartil:  154.5

Kuartil ke-1

In [13]:
q1 = np.percentile(xy, 25)
print('kuartil ke-1 = ', q1)

kuartil ke-1 =  147.0

Kuartil ke-2

In [14]:
q2 = np.percentile(xy, 50)
print('kuartil ke-2 = ', q2)

kuartil ke-2 =  154.5

Kuartil ke-3

In [15]:
q3 = np.percentile(xy, 75)
print('kuartil ke-3 = ', q3)

kuartil ke-3 =  164.0

Desil

In [16]:
D = np.percentile(xy, np.arange(0, 100, 10))
for ind, data in enumerate(D):
  print(f'Desil ke-{ind+1} = {data}')

Desil ke-1 = 138.0
Desil ke-2 = 142.9
Desil ke-3 = 145.8
Desil ke-4 = 149.0
Desil ke-5 = 151.6
Desil ke-6 = 154.5
Desil ke-7 = 158.39999999999998
Desil ke-8 = 162.0
Desil ke-9 = 167.0
Desil ke-10 = 172.10000000000002

Rumus Jangkauan j= xn - x1

In [17]:
Xn = max(xy)
X1 = min(xy)
J = Xn - X1
print(f'Jangkauan data = {J}')

Jangkauan data = 47